- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git.yml
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
    - include: tasks/lsp.yml
    - include: tasks/brave.yml
    - include: tasks/productivity-tools.yml
