# https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04
- name: install docker essentials
  become: true
  apt:
    name: ["apt-transport-https", "ca-certificates"]
  tags:
    - install
    - docker

- name: add docker repo GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
  tags:
    - install
    - docker

- name: add docker repo to apt sources
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  tags:
    - install
    - docker

- name: install docker
  become: true
  apt:
    name: "docker-ce"
  tags:
    - install
    - docker

- name: add user to docker group
  become: true
  shell: sudo usermod -aG docker ${USER}
